services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "C:/work/practicum/sprint1/Data:/var/lib/postgresql/data"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smarthome-network      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telemetry"]
      interval: 10s
      timeout: 5s
      retries: 5

  temperature-api:
    build:
      context: ./temperature-api
      dockerfile: Dockerfile
    container_name: temperature-api
    ports:
      - "8081:8081"
    networks:
      - smarthome-network
      
  old-good-app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

  telemetry-service:
    build: ./telemetry-service
    container_name: telemetry-service
    ports:
      - "8082:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: telemetry
    networks:
      - smarthome-network      
    depends_on:
      postgres:
        condition: service_healthy

  device-control-service:
    build:
      context: ./DeviceControlService
      dockerfile: ./DeviceControlService/Dockerfile
    container_name: device-control-service
    ports:
      - "8083:8080"
    networks:
      - smarthome-network      
    depends_on:
      postgres:
        condition: service_healthy        

volumes:
  postgres_data:
  
networks:
  smarthome-network:
    driver: bridge  